language: c
compiler:
  - gcc
os: linux
dist: bionic

install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  # check environment
  - gcc -v && g++ -v
  - pwd
  # export
  - export GIT_DIR=VAMK-Linked-List
  - export GTEST_DIR=/home/travis/build/nnminh171298/${GIT_DIR}/googletest/googletest
  # get googletest
  - git clone https://github.com/google/googletest.git
  - make

script:
  - ./my_test

after_success:
  - lcov --rc lcov_branch_coverage=1 -c -i -d . -o .coverage.base
  - lcov --rc lcov_branch_coverage=1 -c -d . -o .coverage.run
  - lcov --rc lcov_branch_coverage=1 -d . -a .coverage.base -a .coverage.run -o .coverage.total
  - coveralls-lcov coverage.total

branches:
  only:
    - master
    - additional

notifications:
  recipients:
    - nnminh171298@gmail.com
  email:
    on_success: always
    on_failure: change
