language: c
compiler:
  - gcc
os: linux
dist: trusty

before_script:
    - make test
script:
    - ./my_test
branches:
  only:
    - master
    - additional
notifications:
  recipients:
    - nnminh171298@gmail.fi
  email:
    on_success: always
    on_failure: change
rvm:
  - 9.00
